version: '3.8'

networks: 
  default:
    external: 
      name: dev_network
    
services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube 
    ports:
    - "9001:9000"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "1536M"