version: '3'

networks: 
  elastic: 
    driver: bridge

services:
  fluentd:
    container_name: fluentd
    build: .
    volumes:
      - ./conf:/fluentd/etc
    links:
      - "elasticsearch"
    networks: 
      - elastic
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    volumes:
    - elasticsearchdata:/usr/share/elasticsearch/data:rw
    environment:
      - "discovery.type=single-node"
      # - ELASTICSEARCH_USERNAME=admin
      # - ELASTICSEARCH_PASSWORD=#sigj@sp3r
      # - xpack.security.enabled=true
    ports:
      - 9200:9200
      - 9300:9300
    networks: 
      - elastic
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 3072M
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.1
    container_name: kibana
    # environment:
    #   - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    #   - xpack.reporting.encryptionKey="anykey"
    #   - ELASTICSEARCH_USERNAME=admin
    #   - ELASTICSEARCH_PASSWORD=#sigj@sp3r
    #   - xpack.security.enabled=true
    ports:
    - 5601:5601
    depends_on:
    - elasticsearch 
    networks: 
    - elastic
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 3072M
    restart: unless-stopped

volumes:
  elasticsearchdata:
    driver: local

