version: '3.8'

networks: 
  default:
    external: 
      name: dev_network
    
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
    - "15672:15672"
    - "5672:5672"
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: "2G"
    restart: unless-stopped