version: '3.8'

networks: 
  default:
    external: 
      name: dev_network
    
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
    - "9000:9000"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./Portainer:/data
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "500M"
    restart: always 