version: '3.8'

networks: 
  default:
    external: 
      name: dev_network
    
services:        
  redis:
    container_name: redis
    image: redis
    ports:
    - "6379:6379"
    deploy:
     resources:
       limits:
         cpus: "0.50"
         memory: "200M"
    restart: unless-stopped